// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wasta.Infrastructure.Persistence;

#nullable disable

namespace Wasta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WastaDbContext))]
    [Migration("20260820213627_Localization")]
    partial class Localization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wasta.Domain.Applications.ApplicationFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.HasKey("Id")
                        .HasName("pk_application_file");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_application_file_application_id");

                    b.ToTable("application_file", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Applications.JobApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("description");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<long>("JobPostId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_post_id");

                    b.Property<long>("JobSeekerId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_seeker_id");

                    b.Property<string>("LiveDemoUrl")
                        .HasColumnType("text")
                        .HasColumnName("live_demo_url");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("text")
                        .HasColumnName("project_title");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text")
                        .HasColumnName("repo_url");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job_application");

                    b.HasIndex("JobPostId")
                        .HasDatabaseName("ix_job_application_job_post_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_job_application_status_id");

                    b.HasIndex("JobSeekerId", "JobPostId")
                        .HasDatabaseName("ix_job_application_job_seeker_id_job_post_id");

                    b.ToTable("job_application", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AssessmentForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short>("QuestionCount")
                        .HasColumnType("smallint")
                        .HasColumnName("question_count");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_assessment_form");

                    b.HasIndex("TrackId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_form_track_id_version");

                    b.ToTable("assessment_form", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AssessmentFormQuestion", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("display_order");

                    b.HasKey("FormId", "QuestionId")
                        .HasName("pk_assessment_form_question");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_assessment_form_question_question_id");

                    b.ToTable("assessment_form_question", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Attempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<long>("JobSeekerId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_seeker_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("Id")
                        .HasName("pk_attempt");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_attempt_form_id");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_attempt_track_id");

                    b.HasIndex("JobSeekerId", "TrackId", "StartedAt")
                        .HasDatabaseName("ix_attempt_job_seeker_id_track_id_started_at");

                    b.ToTable("attempt", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AttemptAnswer", b =>
                {
                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<bool>("FlaggedForReview")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged_for_review");

                    b.Property<long?>("SelectedOptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("selected_option_id");

                    b.HasKey("AttemptId", "QuestionId")
                        .HasName("pk_attempt_answer");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_attempt_answer_question_id");

                    b.HasIndex("SelectedOptionId")
                        .HasDatabaseName("ix_attempt_answer_selected_option_id");

                    b.ToTable("attempt_answer", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AttemptScore", b =>
                {
                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<short>("OverallPercent")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_percent");

                    b.Property<short?>("Percentile")
                        .HasColumnType("smallint")
                        .HasColumnName("percentile");

                    b.Property<int>("RuleVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version_id");

                    b.HasKey("AttemptId")
                        .HasName("pk_attempt_score");

                    b.HasIndex("RuleVersionId")
                        .HasDatabaseName("ix_attempt_score_rule_version_id");

                    b.ToTable("attempt_score", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AttemptSectionScore", b =>
                {
                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<int?>("BandId")
                        .HasColumnType("integer")
                        .HasColumnName("band_id");

                    b.Property<short>("Percent")
                        .HasColumnType("smallint")
                        .HasColumnName("percent");

                    b.HasKey("AttemptId", "SectionId")
                        .HasName("pk_attempt_section_score");

                    b.HasIndex("BandId")
                        .HasDatabaseName("ix_attempt_section_score_band_id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_attempt_section_score_section_id");

                    b.ToTable("attempt_section_score", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short?>("Difficulty")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("Id")
                        .HasName("pk_question");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_question_section_id");

                    b.HasIndex("TrackId", "SectionId")
                        .HasDatabaseName("ix_question_track_id_section_id");

                    b.ToTable("question", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.QuestionOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_question_option");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_option_question_id");

                    b.ToTable("question_option", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.ScoreBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("MaxPercent")
                        .HasColumnType("smallint")
                        .HasColumnName("max_percent");

                    b.Property<short>("MinPercent")
                        .HasColumnType("smallint")
                        .HasColumnName("min_percent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RuleVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version_id");

                    b.HasKey("Id")
                        .HasName("pk_score_band");

                    b.HasIndex("RuleVersionId")
                        .HasDatabaseName("ix_score_band_rule_version_id");

                    b.ToTable("score_band", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.ScoringRuleVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_scoring_rule_version");

                    b.HasIndex("TrackId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_rule_version_track_id_version");

                    b.ToTable("scoring_rule_version", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("Id")
                        .HasName("pk_section");

                    b.HasIndex("TrackId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_section_track_id_name");

                    b.ToTable("section", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.SectionBandFeedback", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<int>("BandId")
                        .HasColumnType("integer")
                        .HasColumnName("band_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.HasKey("SectionId", "BandId")
                        .HasName("pk_section_band_feedback");

                    b.HasIndex("BandId")
                        .HasDatabaseName("ix_section_band_feedback_band_id");

                    b.ToTable("section_band_feedback", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.SectionWeight", b =>
                {
                    b.Property<int>("RuleVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version_id");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("weight");

                    b.HasKey("RuleVersionId", "SectionId")
                        .HasName("pk_section_weight");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_section_weight_section_id");

                    b.ToTable("section_weight", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_log_actor_user_id");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_created_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Audit.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryState")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_state");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("DeliveryState", "CreatedAt")
                        .HasDatabaseName("ix_notification_delivery_state_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notification_user_id_created_at")
                        .HasFilter("read_at IS NULL");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.ApplicationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_application_status");

                    b.ToTable("application_status", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_employment_type");

                    b.ToTable("employment_type", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_industry");

                    b.ToTable("industry", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_payment_method");

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skill");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_name");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_track");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_track_slug");

                    b.ToTable("track", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Catalog.WorkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_work_type");

                    b.ToTable("work_type", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Companies.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanySize")
                        .HasColumnType("text")
                        .HasColumnName("company_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("integer")
                        .HasColumnName("industry_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<string>("RejectionNote")
                        .HasColumnType("text")
                        .HasColumnName("rejection_note");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("VerificationState")
                        .HasColumnType("integer")
                        .HasColumnName("verification_state");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<long?>("VerifiedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("verified_by_user_id");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.HasIndex("IndustryId")
                        .HasDatabaseName("ix_company_industry_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_company_normalized_name");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_user_id");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Companies.CompanyDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.HasKey("Id")
                        .HasName("pk_company_document");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_document_company_id");

                    b.ToTable("company_document", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Credits.CreditLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_credit_ledger_entry");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_credit_ledger_entry_actor_user_id");

                    b.HasIndex("CompanyId", "CreatedAt")
                        .HasDatabaseName("ix_credit_ledger_entry_company_id_created_at");

                    b.ToTable("credit_ledger_entry", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Credits.CreditTopUpRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("credits_requested");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<long?>("LedgerEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_entry_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_credit_topup_request");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_credit_topup_request_company_id");

                    b.HasIndex("LedgerEntryId")
                        .HasDatabaseName("ix_credit_topup_request_ledger_entry_id");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_credit_topup_request_payment_method_id");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_credit_topup_request_reviewed_by_user_id");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("ix_credit_topup_request_state_created_at");

                    b.ToTable("credit_topup_request", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Credits.ProfileUnlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("JobSeekerId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_seeker_id");

                    b.Property<long>("LedgerEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_entry_id");

                    b.HasKey("Id")
                        .HasName("pk_profile_unlock");

                    b.HasIndex("LedgerEntryId")
                        .HasDatabaseName("ix_profile_unlock_ledger_entry_id");

                    b.HasIndex("CompanyId", "JobSeekerId")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_unlock_company_id_job_seeker_id");

                    b.HasIndex("JobSeekerId", "CreatedAt")
                        .HasDatabaseName("ix_profile_unlock_job_seeker_id_created_at");

                    b.ToTable("profile_unlock", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_token_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Identity.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_email");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Jobs.JobPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EmploymentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("employment_type_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("ProjectBrief")
                        .HasColumnType("text")
                        .HasColumnName("project_brief");

                    b.Property<DateOnly?>("ProjectDeadline")
                        .HasColumnType("date")
                        .HasColumnName("project_deadline");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("salary_currency")
                        .IsFixedLength();

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary_min");

                    b.Property<string>("SalaryPeriod")
                        .HasColumnType("text")
                        .HasColumnName("salary_period");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.Property<int?>("WorkTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("work_type_id");

                    b.HasKey("Id")
                        .HasName("pk_job_post");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_job_post_company_id")
                        .HasFilter("is_active");

                    b.HasIndex("EmploymentTypeId")
                        .HasDatabaseName("ix_job_post_employment_type_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_job_post_location_id");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_job_post_track_id")
                        .HasFilter("is_active");

                    b.HasIndex("WorkTypeId")
                        .HasDatabaseName("ix_job_post_work_type_id");

                    b.ToTable("job_post", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Jobs.JobPostFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<long>("JobPostId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_post_id");

                    b.HasKey("Id")
                        .HasName("pk_job_post_file");

                    b.HasIndex("JobPostId")
                        .HasDatabaseName("ix_job_post_file_job_post_id");

                    b.ToTable("job_post_file", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Jobs.JobPostSkill", b =>
                {
                    b.Property<long>("JobPostId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_post_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("JobPostId", "SkillId")
                        .HasName("pk_job_post_skill");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_job_post_skill_skill_id");

                    b.ToTable("job_post_skill", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Localization.LocalizedText", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("EntityType", "EntityId", "Field", "Language")
                        .HasName("pk_localized_text");

                    b.HasIndex("Language")
                        .HasDatabaseName("ix_localized_text_language");

                    b.ToTable("localized_text", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Seekers.JobSeeker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_job_seeker");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_job_seeker_track_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_seeker_user_id");

                    b.ToTable("job_seeker", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Seekers.JobSeekerProfile", b =>
                {
                    b.Property<long>("JobSeekerId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_seeker_id");

                    b.Property<string>("Availability")
                        .HasColumnType("text")
                        .HasColumnName("availability");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset?>("CvUploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cv_uploaded_at");

                    b.Property<string>("CvUrl")
                        .HasColumnType("text")
                        .HasColumnName("cv_url");

                    b.Property<short?>("GraduationYear")
                        .HasColumnType("smallint")
                        .HasColumnName("graduation_year");

                    b.Property<int?>("PreferredWorkTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_work_type_id");

                    b.Property<short>("ProfileStrength")
                        .HasColumnType("smallint")
                        .HasColumnName("profile_strength");

                    b.Property<string>("University")
                        .HasColumnType("text")
                        .HasColumnName("university");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VisibleToCompanies")
                        .HasColumnType("boolean")
                        .HasColumnName("visible_to_companies");

                    b.HasKey("JobSeekerId")
                        .HasName("pk_job_seeker_profile");

                    b.HasIndex("PreferredWorkTypeId")
                        .HasDatabaseName("ix_job_seeker_profile_preferred_work_type_id");

                    b.ToTable("job_seeker_profile", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Seekers.JobSeekerSkill", b =>
                {
                    b.Property<long>("JobSeekerId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_seeker_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("JobSeekerId", "SkillId")
                        .HasName("pk_job_seeker_skill");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_job_seeker_skill_skill_id");

                    b.ToTable("job_seeker_skill", (string)null);
                });

            modelBuilder.Entity("Wasta.Domain.Applications.ApplicationFile", b =>
                {
                    b.HasOne("Wasta.Domain.Applications.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_file_job_applications_application_id");
                });

            modelBuilder.Entity("Wasta.Domain.Applications.JobApplication", b =>
                {
                    b.HasOne("Wasta.Domain.Jobs.JobPost", null)
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_application_job_posts_job_post_id");

                    b.HasOne("Wasta.Domain.Seekers.JobSeeker", null)
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_application_job_seekers_job_seeker_id");

                    b.HasOne("Wasta.Domain.Catalog.ApplicationStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_application_application_status_status_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AssessmentForm", b =>
                {
                    b.HasOne("Wasta.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_form_tracks_track_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AssessmentFormQuestion", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.AssessmentForm", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_form_question_assessment_form_form_id");

                    b.HasOne("Wasta.Domain.Assessments.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_form_question_questions_question_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Attempt", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.AssessmentForm", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_assessment_form_form_id");

                    b.HasOne("Wasta.Domain.Seekers.JobSeeker", null)
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_job_seekers_job_seeker_id");

                    b.HasOne("Wasta.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_tracks_track_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AttemptAnswer", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.Attempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_answer_attempts_attempt_id");

                    b.HasOne("Wasta.Domain.Assessments.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_answer_questions_question_id");

                    b.HasOne("Wasta.Domain.Assessments.QuestionOption", null)
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attempt_answer_question_options_selected_option_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AttemptScore", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.Attempt", null)
                        .WithOne()
                        .HasForeignKey("Wasta.Domain.Assessments.AttemptScore", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_score_attempt_attempt_id");

                    b.HasOne("Wasta.Domain.Assessments.ScoringRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_score_scoring_rule_versions_rule_version_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.AttemptSectionScore", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_section_score_attempt_attempt_id");

                    b.HasOne("Wasta.Domain.Assessments.ScoreBand", null)
                        .WithMany()
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attempt_section_score_score_bands_band_id");

                    b.HasOne("Wasta.Domain.Assessments.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_section_score_sections_section_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Question", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_question_sections_section_id");

                    b.HasOne("Wasta.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_tracks_track_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.QuestionOption", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_option_question_question_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.ScoreBand", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.ScoringRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_band_scoring_rule_versions_rule_version_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.ScoringRuleVersion", b =>
                {
                    b.HasOne("Wasta.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_rule_version_tracks_track_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Section", b =>
                {
                    b.HasOne("Wasta.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_tracks_track_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.SectionBandFeedback", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.ScoreBand", null)
                        .WithMany()
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_band_feedback_score_band_band_id");

                    b.HasOne("Wasta.Domain.Assessments.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_band_feedback_sections_section_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.SectionWeight", b =>
                {
                    b.HasOne("Wasta.Domain.Assessments.ScoringRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_weight_scoring_rule_version_rule_version_id");

                    b.HasOne("Wasta.Domain.Assessments.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_weight_section_section_id");
                });

            modelBuilder.Entity("Wasta.Domain.Audit.AuditLogEntry", b =>
                {
                    b.HasOne("Wasta.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_log_user_accounts_actor_user_id");
                });

            modelBuilder.Entity("Wasta.Domain.Audit.Notification", b =>
                {
                    b.HasOne("Wasta.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user_accounts_user_id");
                });

            modelBuilder.Entity("Wasta.Domain.Companies.Company", b =>
                {
                    b.HasOne("Wasta.Domain.Catalog.Industry", null)
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_company_industries_industry_id");

                    b.HasOne("Wasta.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_user_accounts_user_id");
                });

            modelBuilder.Entity("Wasta.Domain.Companies.CompanyDocument", b =>
                {
                    b.HasOne("Wasta.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_document_company_company_id");
                });

            modelBuilder.Entity("Wasta.Domain.Credits.CreditLedgerEntry", b =>
                {
                    b.HasOne("Wasta.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credit_ledger_entry_user_accounts_actor_user_id");

                    b.HasOne("Wasta.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_ledger_entry_company_company_id");
                });

            modelBuilder.Entity("Wasta.Domain.Credits.CreditTopUpRequest", b =>
                {
                    b.HasOne("Wasta.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_topup_request_company_company_id");

                    b.HasOne("Wasta.Domain.Credits.CreditLedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credit_topup_request_credit_ledger_entry_ledger_entry_id");

                    b.HasOne("Wasta.Domain.Catalog.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_topup_request_payment_methods_payment_method_id");

                    b.HasOne("Wasta.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credit_topup_request_user_accounts_reviewed_by_user_id");
                });

            modelBuilder.Entity("Wasta.Domain.Credits.ProfileUnlock", b =>
                {
                    b.HasOne("Wasta.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_unlock_company_company_id");

                    b.HasOne("Wasta.Domain.Seekers.JobSeeker", null)
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_unlock_job_seeker_job_seeker_id");

                    b.HasOne("Wasta.Domain.Credits.CreditLedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profile_unlock_credit_ledger_entry_ledger_entry_id");
                });

            modelBuilder.Entity("Wasta.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Wasta.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_accounts_user_id");
                });

            modelBuilder.Entity("Wasta.Domain.Jobs.JobPost", b =>
                {
                    b.HasOne("Wasta.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_post_company_company_id");

                    b.HasOne("Wasta.Domain.Catalog.EmploymentType", null)
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_job_post_employment_type_employment_type_id");

                    b.HasOne("Wasta.Domain.Catalog.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_job_post_locations_location_id");

                    b.HasOne("Wasta.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_post_tracks_track_id");

                    b.HasOne("Wasta.Domain.Catalog.WorkType", null)
                        .WithMany()
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_job_post_work_types_work_type_id");
                });

            modelBuilder.Entity("Wasta.Domain.Jobs.JobPostFile", b =>
                {
                    b.HasOne("Wasta.Domain.Jobs.JobPost", null)
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_post_file_job_post_job_post_id");
                });

            modelBuilder.Entity("Wasta.Domain.Jobs.JobPostSkill", b =>
                {
                    b.HasOne("Wasta.Domain.Jobs.JobPost", null)
                        .WithMany()
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_post_skill_job_post_job_post_id");

                    b.HasOne("Wasta.Domain.Catalog.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_post_skill_skills_skill_id");
                });

            modelBuilder.Entity("Wasta.Domain.Seekers.JobSeeker", b =>
                {
                    b.HasOne("Wasta.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_job_seeker_tracks_track_id");

                    b.HasOne("Wasta.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_seeker_user_accounts_user_id");
                });

            modelBuilder.Entity("Wasta.Domain.Seekers.JobSeekerProfile", b =>
                {
                    b.HasOne("Wasta.Domain.Seekers.JobSeeker", null)
                        .WithOne("Profile")
                        .HasForeignKey("Wasta.Domain.Seekers.JobSeekerProfile", "JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_seeker_profile_job_seeker_job_seeker_id");

                    b.HasOne("Wasta.Domain.Catalog.WorkType", null)
                        .WithMany()
                        .HasForeignKey("PreferredWorkTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_job_seeker_profile_work_types_preferred_work_type_id");
                });

            modelBuilder.Entity("Wasta.Domain.Seekers.JobSeekerSkill", b =>
                {
                    b.HasOne("Wasta.Domain.Seekers.JobSeeker", null)
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_seeker_skill_job_seeker_job_seeker_id");

                    b.HasOne("Wasta.Domain.Catalog.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_seeker_skill_skills_skill_id");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Attempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Wasta.Domain.Assessments.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Wasta.Domain.Seekers.JobSeeker", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
